language: python

python:
  - 3.6
install:
  - pip install -r requirements.txt

env:
  - DJANGO=2.2.7

before_install:
  - export SETTINGS_ENV=TEST
  - export PYTHONPATH=$HOME/builds/<my-github-username>/<my-github-repo>
  - export PIP_USE_MIRRORS=true
  - pip install django==$DJANGO --quiet

script:
  - python manage.py test